### PR TITLE
esxi_monitor.pl: check for datastructure to be non-empty before access, ...

### PR DESCRIPTION
**Pull request by turingmachine**
...otherwise get_info() fails silently on empty values

### CODE REVIEW

**Comment by ericenns** [comment]
Wouldn't it be better to test for existence of $$values[0][0]->value

As it would still fail if @values has an empty array at index 0.

**Comment by turingmachine** [comment]
Yes this is true. That was the idea at first. Turned out i suck now at Perl, even though i did once a project with "object oriented" Perl. Will create another pull request with an enhanced version.

**Comment by turingmachine** [comment]
So i checked for all the things:
````
if (defined($values) && scalar @$values && scalar  && exists $$values[0][0]->{value}) {
````

figured this will do the trick as well:
```
if (defined($values) && exists $$values[0][0]->{value}) {
```

Any objections to the latter one? Otherwise I create a new pull request.

**Comment by ericenns** [comment]
The later expression looks good to me.

**Comment by turingmachine** [comment]
This pull request now contains and addtional commit.

**Comment by ericenns** [comment]
Looks good, thanks for your contribution

**Comment by Mattikin** [comment]
Thanks for the fix/enhancement.

I have also updated the Wiki Page of the ZenPack.

**Pull request merged**
